[project]
name = "elsci-peaksel-sdk"
version = "1.0.0"
description = "SDK to upload and manage chromatographic injections and other data in Elsci Peaksel"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT License"}

dependencies = [
    "urllib3==2.0.2",
]
